env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 8
rules:
  no-useless-escape: 0
  no-inner-declarations: 0
  no-console: 0
  no-unused-vars: 0
  no-cond-assign: 0
  no-unexpected-multiline: 0
  linebreak-style:
    - error
    - unix
